[target.mipsel-unknown-none]
rustflags = ["-C", "link-arg=-T device.x",
             "-C", "relocation-model=static"]


[build]
target= "mipsel-unknown-none"

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]