/* ISR symbols for MIPS; generated by svd2devicex */

/* IRQ vector #0 */
PROVIDE(CORE_TIMER = _default_isr_fn);
PROVIDE(CORE_TIMER_CONTEXT = _isr_context);
_vector_0_fn = CORE_TIMER;
_vector_0_context = CORE_TIMER_CONTEXT;

/* IRQ vector #1 */
PROVIDE(CORE_SOFTWARE_0 = _default_isr_fn);
PROVIDE(CORE_SOFTWARE_0_CONTEXT = _isr_context);
_vector_1_fn = CORE_SOFTWARE_0;
_vector_1_context = CORE_SOFTWARE_0_CONTEXT;

/* IRQ vector #2 */
PROVIDE(CORE_SOFTWARE_1 = _default_isr_fn);
PROVIDE(CORE_SOFTWARE_1_CONTEXT = _isr_context);
_vector_2_fn = CORE_SOFTWARE_1;
_vector_2_context = CORE_SOFTWARE_1_CONTEXT;

/* IRQ vector #3 */
PROVIDE(EXTERNAL_0 = _default_isr_fn);
PROVIDE(EXTERNAL_0_CONTEXT = _isr_context);
_vector_3_fn = EXTERNAL_0;
_vector_3_context = EXTERNAL_0_CONTEXT;

/* IRQ vector #4 */
PROVIDE(TIMER_1 = _default_isr_fn);
PROVIDE(TIMER_1_CONTEXT = _isr_context);
_vector_4_fn = TIMER_1;
_vector_4_context = TIMER_1_CONTEXT;

/* IRQ vector #5 */
PROVIDE(INPUT_CAPTURE_1_ERROR = _default_isr_fn);
PROVIDE(INPUT_CAPTURE_1_ERROR_CONTEXT = _isr_context);
_vector_5_fn = INPUT_CAPTURE_1_ERROR;
_vector_5_context = INPUT_CAPTURE_1_ERROR_CONTEXT;

/* IRQ vector #6 */
PROVIDE(INPUT_CAPTURE_1 = _default_isr_fn);
PROVIDE(INPUT_CAPTURE_1_CONTEXT = _isr_context);
_vector_6_fn = INPUT_CAPTURE_1;
_vector_6_context = INPUT_CAPTURE_1_CONTEXT;

/* IRQ vector #7 */
PROVIDE(OUTPUT_COMPARE_1 = _default_isr_fn);
PROVIDE(OUTPUT_COMPARE_1_CONTEXT = _isr_context);
_vector_7_fn = OUTPUT_COMPARE_1;
_vector_7_context = OUTPUT_COMPARE_1_CONTEXT;

/* IRQ vector #8 */
PROVIDE(EXTERNAL_1 = _default_isr_fn);
PROVIDE(EXTERNAL_1_CONTEXT = _isr_context);
_vector_8_fn = EXTERNAL_1;
_vector_8_context = EXTERNAL_1_CONTEXT;

/* IRQ vector #9 */
PROVIDE(TIMER_2 = _default_isr_fn);
PROVIDE(TIMER_2_CONTEXT = _isr_context);
_vector_9_fn = TIMER_2;
_vector_9_context = TIMER_2_CONTEXT;

/* IRQ vector #10 */
PROVIDE(INPUT_CAPTURE_2_ERROR = _default_isr_fn);
PROVIDE(INPUT_CAPTURE_2_ERROR_CONTEXT = _isr_context);
_vector_10_fn = INPUT_CAPTURE_2_ERROR;
_vector_10_context = INPUT_CAPTURE_2_ERROR_CONTEXT;

/* IRQ vector #11 */
PROVIDE(INPUT_CAPTURE_2 = _default_isr_fn);
PROVIDE(INPUT_CAPTURE_2_CONTEXT = _isr_context);
_vector_11_fn = INPUT_CAPTURE_2;
_vector_11_context = INPUT_CAPTURE_2_CONTEXT;

/* IRQ vector #12 */
PROVIDE(OUTPUT_COMPARE_2 = _default_isr_fn);
PROVIDE(OUTPUT_COMPARE_2_CONTEXT = _isr_context);
_vector_12_fn = OUTPUT_COMPARE_2;
_vector_12_context = OUTPUT_COMPARE_2_CONTEXT;

/* IRQ vector #13 */
PROVIDE(EXTERNAL_2 = _default_isr_fn);
PROVIDE(EXTERNAL_2_CONTEXT = _isr_context);
_vector_13_fn = EXTERNAL_2;
_vector_13_context = EXTERNAL_2_CONTEXT;

/* IRQ vector #14 */
PROVIDE(TIMER_3 = _default_isr_fn);
PROVIDE(TIMER_3_CONTEXT = _isr_context);
_vector_14_fn = TIMER_3;
_vector_14_context = TIMER_3_CONTEXT;

/* IRQ vector #15 */
PROVIDE(INPUT_CAPTURE_3_ERROR = _default_isr_fn);
PROVIDE(INPUT_CAPTURE_3_ERROR_CONTEXT = _isr_context);
_vector_15_fn = INPUT_CAPTURE_3_ERROR;
_vector_15_context = INPUT_CAPTURE_3_ERROR_CONTEXT;

/* IRQ vector #16 */
PROVIDE(INPUT_CAPTURE_3 = _default_isr_fn);
PROVIDE(INPUT_CAPTURE_3_CONTEXT = _isr_context);
_vector_16_fn = INPUT_CAPTURE_3;
_vector_16_context = INPUT_CAPTURE_3_CONTEXT;

/* IRQ vector #17 */
PROVIDE(OUTPUT_COMPARE_3 = _default_isr_fn);
PROVIDE(OUTPUT_COMPARE_3_CONTEXT = _isr_context);
_vector_17_fn = OUTPUT_COMPARE_3;
_vector_17_context = OUTPUT_COMPARE_3_CONTEXT;

/* IRQ vector #18 */
PROVIDE(EXTERNAL_3 = _default_isr_fn);
PROVIDE(EXTERNAL_3_CONTEXT = _isr_context);
_vector_18_fn = EXTERNAL_3;
_vector_18_context = EXTERNAL_3_CONTEXT;

/* IRQ vector #19 */
PROVIDE(TIMER_4 = _default_isr_fn);
PROVIDE(TIMER_4_CONTEXT = _isr_context);
_vector_19_fn = TIMER_4;
_vector_19_context = TIMER_4_CONTEXT;

/* IRQ vector #20 */
PROVIDE(INPUT_CAPTURE_4_ERROR = _default_isr_fn);
PROVIDE(INPUT_CAPTURE_4_ERROR_CONTEXT = _isr_context);
_vector_20_fn = INPUT_CAPTURE_4_ERROR;
_vector_20_context = INPUT_CAPTURE_4_ERROR_CONTEXT;

/* IRQ vector #21 */
PROVIDE(INPUT_CAPTURE_4 = _default_isr_fn);
PROVIDE(INPUT_CAPTURE_4_CONTEXT = _isr_context);
_vector_21_fn = INPUT_CAPTURE_4;
_vector_21_context = INPUT_CAPTURE_4_CONTEXT;

/* IRQ vector #22 */
PROVIDE(OUTPUT_COMPARE_4 = _default_isr_fn);
PROVIDE(OUTPUT_COMPARE_4_CONTEXT = _isr_context);
_vector_22_fn = OUTPUT_COMPARE_4;
_vector_22_context = OUTPUT_COMPARE_4_CONTEXT;

/* IRQ vector #23 */
PROVIDE(EXTERNAL_4 = _default_isr_fn);
PROVIDE(EXTERNAL_4_CONTEXT = _isr_context);
_vector_23_fn = EXTERNAL_4;
_vector_23_context = EXTERNAL_4_CONTEXT;

/* IRQ vector #24 */
PROVIDE(TIMER_5 = _default_isr_fn);
PROVIDE(TIMER_5_CONTEXT = _isr_context);
_vector_24_fn = TIMER_5;
_vector_24_context = TIMER_5_CONTEXT;

/* IRQ vector #25 */
PROVIDE(INPUT_CAPTURE_5_ERROR = _default_isr_fn);
PROVIDE(INPUT_CAPTURE_5_ERROR_CONTEXT = _isr_context);
_vector_25_fn = INPUT_CAPTURE_5_ERROR;
_vector_25_context = INPUT_CAPTURE_5_ERROR_CONTEXT;

/* IRQ vector #26 */
PROVIDE(INPUT_CAPTURE_5 = _default_isr_fn);
PROVIDE(INPUT_CAPTURE_5_CONTEXT = _isr_context);
_vector_26_fn = INPUT_CAPTURE_5;
_vector_26_context = INPUT_CAPTURE_5_CONTEXT;

/* IRQ vector #27 */
PROVIDE(OUTPUT_COMPARE_5 = _default_isr_fn);
PROVIDE(OUTPUT_COMPARE_5_CONTEXT = _isr_context);
_vector_27_fn = OUTPUT_COMPARE_5;
_vector_27_context = OUTPUT_COMPARE_5_CONTEXT;

/* IRQ vector #28 */
PROVIDE(TIMER_6 = _default_isr_fn);
PROVIDE(TIMER_6_CONTEXT = _isr_context);
_vector_28_fn = TIMER_6;
_vector_28_context = TIMER_6_CONTEXT;

/* IRQ vector #29 */
PROVIDE(INPUT_CAPTURE_6_ERROR = _default_isr_fn);
PROVIDE(INPUT_CAPTURE_6_ERROR_CONTEXT = _isr_context);
_vector_29_fn = INPUT_CAPTURE_6_ERROR;
_vector_29_context = INPUT_CAPTURE_6_ERROR_CONTEXT;

/* IRQ vector #30 */
PROVIDE(INPUT_CAPTURE_6 = _default_isr_fn);
PROVIDE(INPUT_CAPTURE_6_CONTEXT = _isr_context);
_vector_30_fn = INPUT_CAPTURE_6;
_vector_30_context = INPUT_CAPTURE_6_CONTEXT;

/* IRQ vector #31 */
PROVIDE(OUTPUT_COMPARE_6 = _default_isr_fn);
PROVIDE(OUTPUT_COMPARE_6_CONTEXT = _isr_context);
_vector_31_fn = OUTPUT_COMPARE_6;
_vector_31_context = OUTPUT_COMPARE_6_CONTEXT;

/* IRQ vector #32 */
PROVIDE(TIMER_7 = _default_isr_fn);
PROVIDE(TIMER_7_CONTEXT = _isr_context);
_vector_32_fn = TIMER_7;
_vector_32_context = TIMER_7_CONTEXT;

/* IRQ vector #33 */
PROVIDE(INPUT_CAPTURE_7_ERROR = _default_isr_fn);
PROVIDE(INPUT_CAPTURE_7_ERROR_CONTEXT = _isr_context);
_vector_33_fn = INPUT_CAPTURE_7_ERROR;
_vector_33_context = INPUT_CAPTURE_7_ERROR_CONTEXT;

/* IRQ vector #34 */
PROVIDE(INPUT_CAPTURE_7 = _default_isr_fn);
PROVIDE(INPUT_CAPTURE_7_CONTEXT = _isr_context);
_vector_34_fn = INPUT_CAPTURE_7;
_vector_34_context = INPUT_CAPTURE_7_CONTEXT;

/* IRQ vector #35 */
PROVIDE(OUTPUT_COMPARE_7 = _default_isr_fn);
PROVIDE(OUTPUT_COMPARE_7_CONTEXT = _isr_context);
_vector_35_fn = OUTPUT_COMPARE_7;
_vector_35_context = OUTPUT_COMPARE_7_CONTEXT;

/* IRQ vector #36 */
PROVIDE(TIMER_8 = _default_isr_fn);
PROVIDE(TIMER_8_CONTEXT = _isr_context);
_vector_36_fn = TIMER_8;
_vector_36_context = TIMER_8_CONTEXT;

/* IRQ vector #37 */
PROVIDE(INPUT_CAPTURE_8_ERROR = _default_isr_fn);
PROVIDE(INPUT_CAPTURE_8_ERROR_CONTEXT = _isr_context);
_vector_37_fn = INPUT_CAPTURE_8_ERROR;
_vector_37_context = INPUT_CAPTURE_8_ERROR_CONTEXT;

/* IRQ vector #38 */
PROVIDE(INPUT_CAPTURE_8 = _default_isr_fn);
PROVIDE(INPUT_CAPTURE_8_CONTEXT = _isr_context);
_vector_38_fn = INPUT_CAPTURE_8;
_vector_38_context = INPUT_CAPTURE_8_CONTEXT;

/* IRQ vector #39 */
PROVIDE(OUTPUT_COMPARE_8 = _default_isr_fn);
PROVIDE(OUTPUT_COMPARE_8_CONTEXT = _isr_context);
_vector_39_fn = OUTPUT_COMPARE_8;
_vector_39_context = OUTPUT_COMPARE_8_CONTEXT;

/* IRQ vector #40 */
PROVIDE(TIMER_9 = _default_isr_fn);
PROVIDE(TIMER_9_CONTEXT = _isr_context);
_vector_40_fn = TIMER_9;
_vector_40_context = TIMER_9_CONTEXT;

/* IRQ vector #41 */
PROVIDE(INPUT_CAPTURE_9_ERROR = _default_isr_fn);
PROVIDE(INPUT_CAPTURE_9_ERROR_CONTEXT = _isr_context);
_vector_41_fn = INPUT_CAPTURE_9_ERROR;
_vector_41_context = INPUT_CAPTURE_9_ERROR_CONTEXT;

/* IRQ vector #42 */
PROVIDE(INPUT_CAPTURE_9 = _default_isr_fn);
PROVIDE(INPUT_CAPTURE_9_CONTEXT = _isr_context);
_vector_42_fn = INPUT_CAPTURE_9;
_vector_42_context = INPUT_CAPTURE_9_CONTEXT;

/* IRQ vector #43 */
PROVIDE(OUTPUT_COMPARE_9 = _default_isr_fn);
PROVIDE(OUTPUT_COMPARE_9_CONTEXT = _isr_context);
_vector_43_fn = OUTPUT_COMPARE_9;
_vector_43_context = OUTPUT_COMPARE_9_CONTEXT;

/* IRQ vector #44 */
PROVIDE(ADC = _default_isr_fn);
PROVIDE(ADC_CONTEXT = _isr_context);
_vector_44_fn = ADC;
_vector_44_context = ADC_CONTEXT;

/* IRQ vector #45 */
PROVIDE(ADC_FIFO = _default_isr_fn);
PROVIDE(ADC_FIFO_CONTEXT = _isr_context);
_vector_45_fn = ADC_FIFO;
_vector_45_context = ADC_FIFO_CONTEXT;

/* IRQ vector #46 */
PROVIDE(ADC_DC1 = _default_isr_fn);
PROVIDE(ADC_DC1_CONTEXT = _isr_context);
_vector_46_fn = ADC_DC1;
_vector_46_context = ADC_DC1_CONTEXT;

/* IRQ vector #47 */
PROVIDE(ADC_DC2 = _default_isr_fn);
PROVIDE(ADC_DC2_CONTEXT = _isr_context);
_vector_47_fn = ADC_DC2;
_vector_47_context = ADC_DC2_CONTEXT;

/* IRQ vector #48 */
PROVIDE(ADC_DC3 = _default_isr_fn);
PROVIDE(ADC_DC3_CONTEXT = _isr_context);
_vector_48_fn = ADC_DC3;
_vector_48_context = ADC_DC3_CONTEXT;

/* IRQ vector #49 */
PROVIDE(ADC_DC4 = _default_isr_fn);
PROVIDE(ADC_DC4_CONTEXT = _isr_context);
_vector_49_fn = ADC_DC4;
_vector_49_context = ADC_DC4_CONTEXT;

/* IRQ vector #50 */
PROVIDE(ADC_DC5 = _default_isr_fn);
PROVIDE(ADC_DC5_CONTEXT = _isr_context);
_vector_50_fn = ADC_DC5;
_vector_50_context = ADC_DC5_CONTEXT;

/* IRQ vector #51 */
PROVIDE(ADC_DC6 = _default_isr_fn);
PROVIDE(ADC_DC6_CONTEXT = _isr_context);
_vector_51_fn = ADC_DC6;
_vector_51_context = ADC_DC6_CONTEXT;

/* IRQ vector #52 */
PROVIDE(ADC_DF1 = _default_isr_fn);
PROVIDE(ADC_DF1_CONTEXT = _isr_context);
_vector_52_fn = ADC_DF1;
_vector_52_context = ADC_DF1_CONTEXT;

/* IRQ vector #53 */
PROVIDE(ADC_DF2 = _default_isr_fn);
PROVIDE(ADC_DF2_CONTEXT = _isr_context);
_vector_53_fn = ADC_DF2;
_vector_53_context = ADC_DF2_CONTEXT;

/* IRQ vector #54 */
PROVIDE(ADC_DF3 = _default_isr_fn);
PROVIDE(ADC_DF3_CONTEXT = _isr_context);
_vector_54_fn = ADC_DF3;
_vector_54_context = ADC_DF3_CONTEXT;

/* IRQ vector #55 */
PROVIDE(ADC_DF4 = _default_isr_fn);
PROVIDE(ADC_DF4_CONTEXT = _isr_context);
_vector_55_fn = ADC_DF4;
_vector_55_context = ADC_DF4_CONTEXT;

/* IRQ vector #56 */
PROVIDE(ADC_DF5 = _default_isr_fn);
PROVIDE(ADC_DF5_CONTEXT = _isr_context);
_vector_56_fn = ADC_DF5;
_vector_56_context = ADC_DF5_CONTEXT;

/* IRQ vector #57 */
PROVIDE(ADC_DF6 = _default_isr_fn);
PROVIDE(ADC_DF6_CONTEXT = _isr_context);
_vector_57_fn = ADC_DF6;
_vector_57_context = ADC_DF6_CONTEXT;

/* IRQ vector #58 */
PROVIDE(ADC_FAULT = _default_isr_fn);
PROVIDE(ADC_FAULT_CONTEXT = _isr_context);
_vector_58_fn = ADC_FAULT;
_vector_58_context = ADC_FAULT_CONTEXT;

/* IRQ vector #59 */
PROVIDE(ADC_DATA0 = _default_isr_fn);
PROVIDE(ADC_DATA0_CONTEXT = _isr_context);
_vector_59_fn = ADC_DATA0;
_vector_59_context = ADC_DATA0_CONTEXT;

/* IRQ vector #60 */
PROVIDE(ADC_DATA1 = _default_isr_fn);
PROVIDE(ADC_DATA1_CONTEXT = _isr_context);
_vector_60_fn = ADC_DATA1;
_vector_60_context = ADC_DATA1_CONTEXT;

/* IRQ vector #61 */
PROVIDE(ADC_DATA2 = _default_isr_fn);
PROVIDE(ADC_DATA2_CONTEXT = _isr_context);
_vector_61_fn = ADC_DATA2;
_vector_61_context = ADC_DATA2_CONTEXT;

/* IRQ vector #62 */
PROVIDE(ADC_DATA3 = _default_isr_fn);
PROVIDE(ADC_DATA3_CONTEXT = _isr_context);
_vector_62_fn = ADC_DATA3;
_vector_62_context = ADC_DATA3_CONTEXT;

/* IRQ vector #63 */
PROVIDE(ADC_DATA4 = _default_isr_fn);
PROVIDE(ADC_DATA4_CONTEXT = _isr_context);
_vector_63_fn = ADC_DATA4;
_vector_63_context = ADC_DATA4_CONTEXT;

